### ISSUE TITLE
[Planejamento] Planejar Requisitos

### ISSUE THREAD

**Issue by GuilhermeRocha13** [GEDAI-SI/GEDAI-PUC-TIS-2024#14]
Visão geral dos requisitos do sistema com pouco detalhamento.

Documentação sendo feita no google docs, link abaixo:

https://1drv.ms/w/s!Am7dWN76nU8ulqZ21L2TZRDkQfsUcA?e=14Ucqj

**Comment by GabrielDiniz05** [comment]
### Processo 1: Coleta de Dados Climáticos

#### Requisitos Funcionais:

1. O sistema deve permitir a configuração de intervalos de tempo para a coleta de dados climáticos de APIs, ajustando a frequência de acordo com as necessidades do usuário.
2. O sistema deve consolidar dados de diferentes fontes (e.g., OpenWeather, WeatherAPI, Visual Crossing) em um formato único e uniforme, garantindo que todos os parâmetros climáticos necessários (temperatura, umidade, etc.) sejam capturados.

#### Requisitos Não Funcionais:

1. **Confiabilidade:** O sistema deve garantir uma taxa de sucesso de 99,9% na recuperação de dados climáticos de APIs, com tentativas automáticas de reconexão em caso de falha.
2. **Desempenho:** O tempo de resposta para a coleta de dados de uma API não deve exceder 3 segundos em 95% das requisições, mesmo em condições de pico de uso.

---

### Processo 2: Análise de Dados Climáticos

#### Requisitos Funcionais:

1. O sistema deve realizar cálculos automáticos de eficiência energética a cada 24 horas, considerando os dados climáticos coletados e a produção de energia solar.
2. O sistema deve gerar alertas quando forem identificadas anomalias nos padrões de eficiência energética, enviando relatórios automáticos com as possíveis causas e soluções.

#### Requisitos Não Funcionais:

1. **Precisão:** O sistema deve garantir que as previsões de desempenho sejam, no mínimo, 85% precisas, baseadas na modelagem dos dados históricos e climáticos.
2. **Escalabilidade:** O sistema deve ser capaz de suportar a análise simultânea de pelo menos 10 mil painéis solares sem queda de desempenho ou latência.

---

### Processo 3: Monitoramento de Painéis Solares

#### Requisitos Funcionais:

1. O sistema deve realizar o monitoramento contínuo da produção de energia em tempo real e exibir esses dados em dashboards visuais acessíveis aos usuários.
2. O sistema deve integrar-se com sistemas de manutenção para registrar automaticamente anomalias e sugerir ações corretivas quando forem detectados problemas de desempenho.

#### Requisitos Não Funcionais:

1. **Disponibilidade:** O sistema de monitoramento deve ter uma disponibilidade mínima de 99,9% ao longo do ano, garantindo o monitoramento contínuo dos painéis solares.
2. **Compatibilidade:** O sistema deve ser compatível com diferentes marcas e modelos de painéis solares, garantindo a coleta precisa de dados independentemente do hardware utilizado.

---

### Processo 4: Previsão de Desempenho Solar

#### Requisitos Funcionais:

1. O sistema deve gerar previsões diárias e semanais de produção de energia com base nos dados climáticos coletados e no histórico de desempenho dos painéis solares.
2. O sistema deve permitir a exportação de previsões em formatos como CSV e PDF, para facilitar a análise por usuários externos.

#### Requisitos Não Funcionais:

1. **Performance:** O tempo de processamento para gerar previsões de curto e médio prazo não deve exceder 5 segundos por painel solar, mesmo em sistemas com mais de 1 mil painéis.
2. **Usabilidade:** As previsões devem ser apresentadas em gráficos interativos que permitam zoom e filtragem, com uma interface amigável para usuários técnicos e não técnicos.

---

### Processo 5: Geração de Relatórios Detalhados

#### Requisitos Funcionais:

1. O sistema deve gerar relatórios mensais detalhados, contendo indicadores de eficiência energética, produção de energia e redução de emissões de CO₂, comparando com meses anteriores.
2. O sistema deve permitir a customização dos relatórios, de modo que os usuários possam escolher quais métricas e KPIs incluir, dependendo do público-alvo (investidores, gestores, etc.).

#### Requisitos Não Funcionais:

1. **Manutenibilidade:** O sistema deve ter uma estrutura modular para geração de relatórios, permitindo atualizações fáceis e personalizações para atender novos requisitos de relatórios sem impacto no desempenho do sistema.
2. **Segurança:** Os relatórios devem ser criptografados durante o envio e o armazenamento, garantindo que apenas usuários autorizados possam acessá-los.

---

### Processo 6: Emissão de Alertas de Manutenção

#### Requisitos Funcionais:

1. O sistema deve emitir alertas automáticos quando o desempenho dos painéis solares cair abaixo de um determinado limiar, sugerindo manutenção preventiva.
2. O sistema deve notificar as equipes técnicas via e-mail e SMS em caso de anomalias detectadas, permitindo o acompanhamento das ações tomadas.

#### Requisitos Não Funcionais:

1. **Confiabilidade:** O sistema deve ter uma taxa de detecção de anomalias de, no mínimo, 95%, evitando falsos positivos e garantindo que todos os alertas sejam baseados em dados precisos.
2. **Escalabilidade:** O sistema deve ser capaz de emitir e gerenciar alertas para até 100 mil painéis solares simultaneamente, sem comprometer o tempo de resposta ou a qualidade dos alertas.

---
### Processo 7: Cadastro de Usuários

#### Requisitos Funcionais:

1. O sistema deve permitir o cadastro de novos usuários, coletando informações como nome, e-mail, telefone e função (administrador, técnico, cliente).
2. O sistema deve suportar diferentes níveis de acesso com base no tipo de usuário (e.g., administradores têm acesso total, técnicos têm acesso limitado a monitoramento e manutenção, e clientes podem visualizar relatórios).

#### Requisitos Não Funcionais:

1. **Segurança:** O cadastro de usuários deve ser protegido por autenticação forte, como autenticação de dois fatores (2FA), e criptografia de dados sensíveis (e.g., senhas).
2. **Escalabilidade:** O sistema deve ser capaz de suportar até 10 mil usuários cadastrados sem afetar o desempenho geral do sistema, com possibilidade de expansão.

---

### Processo 8: Cadastro de Painéis Solares

#### Requisitos Funcionais:

1. O sistema deve permitir o cadastro de painéis solares, registrando informações como modelo, fabricante, localização geográfica, data de instalação e capacidade de produção.
2. O sistema deve associar cada painel solar a um usuário ou grupo de usuários, permitindo que apenas usuários autorizados monitorem e gerenciem os painéis.

#### Requisitos Não Funcionais:

1. **Compatibilidade:** O sistema deve suportar o cadastro de diferentes tipos de painéis solares de vários fabricantes e modelos, permitindo a interoperabilidade com sistemas de monitoramento e análise.
2. **Usabilidade:** O processo de cadastro de painéis solares deve ser rápido e simples, permitindo que os usuários registrem um novo painel em menos de 2 minutos, com uma interface clara e fácil de navegar.

**Comment by GabrielDiniz05** [comment]
Word: [Sprint 2 - Documentação](https://1drv.ms/w/s!Am7dWN76nU8ulqZ21L2TZRDkQfsUcA?e=14Ucqj)

**Comment by GuilhermeRocha13** [comment]
Bom dia!
Fiz ajustes na documentação em alguns requisitos, abaixo descrevo a razão. 

- Remoção 

Requisito Funcional - 02 Niveis de acesso
Não há necessidade de limitar acesso pois não há funcionalidades que requerem controle único
O gerenciamento dos paineis no sistema será feito por apenas um usuário.

Requisito Funcional - 04 Associação de Painéis a Usuários 
Não será necessário ter grupos de usuário, já que não terão niveis de acesso, um unico usuário é mais eficiente.

- Alteração 

Requisito Funcional - 16 Notificação de Anomalias para Equipes Técnicas 
Alerta será enviado apenas por email

**Comment by GuilhermeRocha13** [comment]
Devemos discutir a viabilidade do requisito funcional 10 "Integração com Sistemas de Manutenção".
É um requisito muito interessante mas não saberei dimensionar tecnicamente sua viabilidade, a principio acho que podemos deixar em stand by, fora da documentação oficial.
