### ISSUE TITLE
[Planejamento] Estudo: Painéis Solares

### ISSUE THREAD

**Issue by GabrielDiniz05** [GEDAI-SI/GEDAI-PUC-TIS-2024#16]
# Objetivo:
O responsável por esta tarefa deve: Realizar um estudo sobre o cadastro de painéis solares, descrevendo quais dados nós devemos mapear para realizar um cadastro de painéis solares no sistema Photon Nest.

Exemplo: 
1 - Modelo
2 - Data de instalação
3 - Data de validade
4 - Fabricante

# Critérios de aceite:
- Documento descrevendo todos os dados que o responsável achar relevante para o cadastro no sistema. (O documento pode ser um comentário neste card.)
- Reunião, definição e documentação dos dados que serão usados no Photon Nest.

## Critérios adicionais:

- Diagrama de classe dos painéis solares.

**Comment by GabrielDiniz05** [comment]
@GuilhermeRocha13 Card criado.

**Comment by GuilhermeRocha13** [comment]
Precisaremos dos seguintes dados para fazer o cálculo de conversão energética:
- Radiação Solar: Quantidade de radiação solar recebida pelo painel. (Temos o dado na weather)
- Área do Painel: Área da superfície do painel solar em metros quadrados (m²).
- Eficiência do Painel: Eficiência do painel na conversão da radiação solar em eletricidade.
- Horas de Sol: Número de horas de sol efetivo por dia.

a eficiencia do painel vai variar com seu tipo, há 3 tipos em vigor:
- Painéis Monocristalinos: Entre 15% e 20%.
- Painéis Policristalinos: Entre 13% e 16%.
- Painéis de Filme Fino: Entre 10% e 12%

---

Dito isso, segue abaixo o diagrama ER com a estrutura da entidade

![Diagrama](https://github.com/GEDAI-SI/GEDAI-PUC-TIS-2024/blob/master/docs/images/Painel-entidade.png)

Qualquer melhoria me comunique, por favor

**Comment by GabrielDiniz05** [comment]
@GuilhermeRocha13 Card Aprovado.
