### ISSUE TITLE
[Planejamento] Estudo: APIs de dados climáticos

### ISSUE THREAD

**Issue by GabrielDiniz05** [GEDAI-SI/GEDAI-PUC-TIS-2024#17]
# Objetivo:
O responsável por esta tarefa deve: Realizar um estudo sobre as APIs de dados climáticos disponíveis na Web, descrevendo quais são os prós e os contras de cada uma. Por fim, o grupo irá decidir qual API será implementada no sistema Photon Nest.

Exemplo: 

1 - API de Fulano
- Prós:
      - Dados em tempo real.
- Contras:
      - É pago.

# Critérios de aceite:
- Documento descrevendo todas as APIs que o responsável achar relevante para o sistema. (O documento pode ser um comentário neste card.)
- Reunião, definição e documentação da API que será usada no Photon Nest.

**Comment by GabrielDiniz05** [comment]
@raicavalcante Card criado.

**Comment by raicavalcante** [comment]
# API's

[Weatherbit](https://www.weatherbit.io/)
Limites do Plano Gratuito:

Requests: 500 chamadas por dia.
Previsão para o futuro: Previsões de 7 dias (mas previsões detalhadas por hora e previsões de 16 dias estão disponíveis apenas em planos pagos).
Histórico: Acesso limitado, mas pode fornecer dados históricos básicos.

Um bom equilíbrio entre a quantidade de chamadas diárias (500) e previsões de (até 7 dias), o que a torna útil. O histórico e as previsões são limitadas, mas atende a uma variedade de cenários de uso.

-----------

[OpenWeatherMap](https://openweathermap.org/)
Limites do Plano Gratuito:

Requests: 60 chamadas por minuto.
Previsão para o futuro: 5 dias de previsão.
Histórico: Dados históricos limitados a condições básicas (dados avançados disponíveis apenas nos planos pagos).

Embora tenha menos previsões para o futuro (5 dias), o limite de 60 chamadas por minuto é excelente para cenários que exigem alta frequência de consultas, como aplicativos com muitos usuários.

-----------

[Weather API da Visual Crossing](https://www.visualcrossing.com/weather-api):
Limites do Plano Gratuito:

Requests: 1.000 chamadas por dia.
Previsão para o futuro: Até 15 dias.
Histórico: Até 3 anos de dados históricos.

1.000 chamadas por dia é o maior limite entre todas, com um histórico de 3 anos, o que é ótimo para análises históricas mais profundas e previsões de até 15 dias, tornando-a uma excelente opção tanto para previsões quanto para consulta de dados históricos.

**Comment by GabrielDiniz05** [comment]
Aprovado.
