### ISSUE TITLE
[Planejamento] Refazer: Descrever detalhadamente cada processo e comprimir o número de processos.

### ISSUE THREAD

**Issue by GabrielDiniz05** [GEDAI-SI/GEDAI-PUC-TIS-2024#18]
# Objetivo:
O responsável por esta tarefa deve: Descreve todos os processos com o máximo de detalhes possível. Além de eliminar processos redundantes e indesejados.

# Critérios de aceite:
- Documento descrevendo todos os processos. (O documento pode ser um comentário neste card.)
- Reunião, apresentando os novos processos.

**Comment by GabrielDiniz05** [comment]
## Processo 1: Cadastro de Usuários 
**Responsável**: Gabriel de Assis Lopes Diniz
**Aprovador**: João Victor Santos Egydio 

O processo de cadastro de usuários permite a criação e gestão de contas, determinando níveis de acesso e garantindo que cada usuário tenha as permissões adequadas para acessar as funcionalidades do sistema. 

Cadastro de Novos Usuários: O sistema permite a inserção de informações como nome, sobrenome, e-mail, data de nascimento. 

### Refinamento Técnico:
Haverá um botão de cadastro na página home do sistema, onde ao clicar, o usuário será redirecionado para o formulário de cadastro, onde ele vai preencher (Nome, Sobrenome, E-mail e Data de Nascimento). Após finalizar o cadastro o usuário será redirecionado para a página principal do sistema.

## Processo 2: Cadastro de Painéis Solares 
**Responsável**: Raí Átila Cavalcante
**Aprovador**: Abdon França Neto 

O processo de cadastro de painéis solares envolve a inserção de informações sobre os equipamentos para que possam ser monitorados e gerenciados pelo sistema. 

Registro de Painéis: O sistema permite o cadastro das seguintes informações: área, endereço, eficiência, modelo, horas de sol. 

Associação a Usuários: Cada painel será vinculado a um usuário, garantindo que apenas pessoas autorizadas possam monitorá-lo.

### Refinamento Técnico:
Assim que o processo 1 for finalizado o usuário será apresentado à página inicial, onde haverá um botão para realizar o cadastro de painel solar, após o usuário clicar no botão ele será redirecionado para o formulário de criação do mesmo. E após a finalização do cadastro do painel solar, o usuário será direcionado para a página de detalhes do painel solar.

## Processo 3: Previsão de Desempenho Solar 
**Responsável**: Guilherme Henrique Pereira Rocha 
**Aprovador**: Gabriel de Assis Lopes Diniz 

Esse processo utiliza modelos preditivos para estimar o desempenho futuro dos painéis solares, com base nas condições climáticas previstas. A previsão é essencial para otimizar a operação e o planejamento energético. As etapas envolvem: 

### Coleta de Dados Climáticos 

A coleta de dados climáticos no aplicativo envolve a obtenção de informações históricas e em tempo real sobre as condições meteorológicas. Para isso, são utilizadas fontes confiáveis, como serviços meteorológicos globais ou regionais (e.g., APIs de serviços como OpenWeather ou WeatherAPI ou a API da Visual Crossing). Esses dados incluem informações sobre temperatura, umidade, precipitação, irradiância solar, velocidade do vento e outros fatores que influenciam na produção de energia solar. 

Serviços Meteorológicos: O aplicativo se conecta periodicamente a APIs de provedores de serviços meteorológicos para recuperar dados sobre as condições atuais e previsões futuras, proporcionando aos usuários uma visão antecipada do clima que pode afetar o desempenho das placas solares. 

### Modelagem Preditiva 

Utilização de algoritmos que analisam os dados climáticos futuros para prever a produção de energia solar em curto e médio prazo. 

### Cálculo do Desempenho Futuro 

Com base nos dados e no histórico de eficiência do sistema, o desempenho esperado é calculado, permitindo ajustes antecipados na operação. 

Visualização de Previsões 

As estimativas de desempenho são apresentadas em relatórios e gráficos, facilitando o planejamento e a tomada de decisões operacionais.

### Refinamento Técnico
Ao fim dos processos 1 e 2, na página de detalhes do painel, o usuário terá a opção de verificar o desempenho solar futuro. Haverá um botão que ao ser clicado uma acionará uma integração que vai receber os dados futuros que serão tratados no sistema, após isso, o usuário será redirecionado para uma página dentro do sistema que mostra os cálculos de desempenho futuro do painel cadastrado.

## Processo 4: Monitoramento de Painéis Solares 
**Responsável**: João Fellipe Alves de Moraes 
**Aprovador**: João Victor Santos Egydio 

Monitoramento contínuo do desempenho dos painéis solares, incluindo produção de energia e status operacional. Este processo é essencial para garantir que os painéis solares estejam operando de maneira eficiente e que os dados coletados sejam precisos para análise e previsão. Abaixo está uma descrição das etapas envolvidas no processo de monitoramento do sistema solar: 

1. Coleta de Dados em Tempo Real 

2. Análise de Desempenho 

3. Identificação de Anomalias e Problemas 

4. Visualização de Dados e Relatórios 

5. Integração com Outros Processos 

### Refinamento Técnico:
Na página de detalhes do painel, informações sobre desempenho, produção de energia e status operacional serão disponibilizadas para o usuário.

## Processo 5: Geração de Relatórios Detalhados 
**Responsável**: Abdon França Neto 
**Aprovador**: Guilherme Henrique Pereira Rocha 

Esse processo envolve a criação de relatórios completos que destacam o impacto do uso da energia solar, com foco na redução de emissões de carbono e na eficiência energética. Esses relatórios são fundamentais para análise de desempenho e demonstração dos benefícios ambientais. As etapas incluem: 

#### Coleta de Dados Operacionais 
Reunião de dados sobre a produção de energia, eficiência dos painéis e consumo energético, além de informações sobre as emissões de carbono evitadas. 

#### Cálculo de Impacto Ambiental 
Análise dos dados coletados para calcular a quantidade de emissões de CO₂ que foi evitada pelo uso de energia solar em comparação com fontes convencionais. 

#### Análise de Eficiência Energética 
Avaliação da eficiência energética dos sistemas solares, destacando variações sazonais, desempenho e possíveis melhorias. 

#### Geração de Relatórios Interativos 
Criação de relatórios detalhados com gráficos, tabelas e indicadores-chave de desempenho (KPIs) que facilitam a visualização do impacto ambiental e da eficiência energética. 

#### Customização para Diferentes Públicos 
Adaptação dos relatórios para atender às necessidades de diferentes públicos, como investidores, gestores e usuários finais, com níveis de detalhamento variados. 

### Refinamento Técnico:
Na página principal do sistema, haverá uma aba de relatórios, onde após o usuário acessar, ele poderá escolher o painel solar que ele quer gerar relatório, filtrar com base no dia, mês e ano e clicar no botão gerar. Após isso será emitido relatórios com base no filtro do usuário, que poderão ser exportados para PDF.

## Processo 6: Emissão de Alertas de Manutenção 
**Responsável**: João Victor Santos Egydio 
**Aprovador**: João Fellipe Alves de Moraes 

Este processo é responsável por identificar e comunicar a necessidade de manutenção preventiva ou corretiva nos sistemas solares. O objetivo é garantir que os painéis solares funcionem de maneira eficiente e evitar falhas ou quedas significativas no desempenho. 

1. Monitoramento Contínuo de Desempenho 
- Coleta de Dados de Monitoramento 
- Análise de Desempenho e Detecção de Anomalias 

2. Identificação de Necessidade de Manutenção 
- Identificação de Anomalias 
- Avaliação da Necessidade de Manutenção 

3. Geração e Emissão de Alertas 
- Geração de Alertas Automatizados 
- Emissão de Alertas aos Usuários 
- Notificação de Equipes Técnicas 

4. Integração com Sistemas de Manutenção 
- Registro de Alertas para Acompanhamento 
- Planejamento de Manutenção Preventiva 

### Refinamento Técnico:
Caso o desempenho do painel cadastrado pelo usuário esteja ruim ou esteja próximo de uma manutenção, o sistema irá enviar um email com o alerta, avisando ao usuário a situação do painel.

**Comment by GabrielDiniz05** [comment]
![Image](https://github.com/user-attachments/assets/f427d57b-6e77-4756-bdf7-b98a0ceba312)

**Comment by GuilhermeRocha13** [comment]
Revisei os processos, ficou muito bom, até atualizei a documentação no repositório. Porem acho válido no processo 5, retirarmos a opção de CSV, não é muito prático pro usuário final ter que abrir um arquivo desse formato. Processar csv pode ser custoso em processamento, pela complexidade pode tomar muito tempo do responsável pela feature. 
O que achas?

**Comment by GuilhermeRocha13** [comment]
Editei seu card removendo a parte do csv
