### ISSUE TITLE
[Documentação] Preencher parte de tecnologias da documentação do projeto

### ISSUE THREAD

**Issue by GabrielDiniz05** [GEDAI-SI/GEDAI-PUC-TIS-2024#19]
# Objetivo:
O responsável por esta tarefa deve: Descrever as tecnologias que serão usadas em cada processo existente e preencher o documento [Sprint - 2](https://1drv.ms/w/s!Am7dWN76nU8ulqZ21L2TZRDkQfsUcA?e=14Ucqj).

### Exemplo:
 Processo - 1
- SpringBoot
- MySQL
- React

# Critérios de aceite:
- Comentário no card com as tecnologias descritas de acordo com cada processo.
- Documento da Sprint - 2 preenchido.

**Comment by GabrielDiniz05** [comment]
# Processo 1: 
**Back-end:** [Spring Boot](https://spring.io/projects/spring-boot), Hibernate, Java; 
**Front-end:** [React](https://react.dev/); 
**Banco de Dados:** [MYSQL](https://dev.mysql.com/downloads/mysql); 

# Processo 2: 
**Back-end:** [Spring Boot](https://spring.io/projects/spring-boot), Hibernate, Java; 
**Front-end:** [React](https://react.dev/); 
**Banco de Dados:** [MYSQL](https://dev.mysql.com/downloads/mysql); 

# Processo 3: 
**Back-end:** [Spring Boot](https://spring.io/projects/spring-boot), Java; 
**API:**  [Weather API](https://www.visualcrossing.com/weather-api);
**Front-end:** [React](https://react.dev/); 
**Banco de Dados:** [MYSQL](https://dev.mysql.com/downloads/mysql); 

# Processo 4: 
**Back-end:** [Spring Boot](https://spring.io/projects/spring-boot), Java; 
**Front-end:** [React](https://react.dev/); 

# Processo 5: 
**Back-end:** [Spring Boot](https://spring.io/projects/spring-boot), Java; 
**Front-end:** [React](https://react.dev/); 
**Banco de Dados:** [MYSQL](https://dev.mysql.com/downloads/mysql); 

# Processo 6: 
**Back-end:** [Spring Boot](https://spring.io/projects/spring-boot), Java;
**Front-end:** [React](https://react.dev/);

**Comment by raicavalcante** [comment]
@GabrielDiniz05 Card Aprovado.
